# Generated by Django 5.1.1 on 2025-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='FSD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Python',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='TOC',
            field=models.IntegerField(default=0),
        ),
    ]
